### ISSUE TITLE
Really confused as to what purpose the 'rl_env_binary' directory serves

### ISSUE THREAD

**Issue by Rubix982** [Dhyeythumar/PPO-algo-with-custom-Unity-environment#2]
Hello!

I think I got everything almost about this repository, and it's really good work done. I was just confused about what problem the `rl_env_binary` was solving. I went inside the directories - but I didn't understand what the files are doing exactly.

I did read the `README.md`, specifically, the "Environment Specific Details", but it doesn't seem to relate to the directory itself.

Help would be appreciated. Thank you!

**Comment by Dhyeythumar** [comment]
Hi @Rubix982, `rl_env_binary` is the folder where all the environment binaries/build/executable files are stored. These executable files are used as follows:
https://github.com/Dhyeythumar/PPO-algo-with-custom-Unity-environment/blob/ad71f421b858f19dd4d3406ccf1ea7e466736b51/env_driver.py#L12-L21

And this folder contains 3 different types of executables:
- Linux Build (This executable is for Linux users)
- Linux headless Build (Can be used if anyone wants to train the environment on Google Colab or any Cloud solution)
- Windows Build (Windows users)

**Comment by Rubix982** [comment]
Thank you so much! I think I got it. Appreciated.
